services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8085:80"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_DATABASE=siesmt
      - DB_USERNAME=admin
      - DB_PASSWORD=admin

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: siesmt
    command: ["postgres", "-c", "port=5433"]
    ports:
        - "5433:5433"
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  minio_data:
  pgdata:
